name: Online Plugin Compiler
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile Jar
        run: |
          if [ -f "gradlew" ]; then
            chmod +x gradlew
            ./gradlew build
          else
            mvn clean package
          fi

      - name: Save Compiled Plugin
        uses: actions/upload-artifact@v4
        with:
          name: CoreProtect-Compiled
          path: |
            **/target/*.jar
            **/build/libs/*.jar
